on: [push]

jobs:
  push-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Cachix
        uses: cachix/cachix-action@v16
        with:
          name: hbnix
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build everything
        run: nix build github:srid/devour-flake -L --no-link --print-out-paths --override-input flake .